### PR TITLE
Fixes for #76, #79, #80, #92, #99, #102, #104, #110, #113, #114, #115, #118, #119, #120, #123, #124

### PR DESCRIPTION
**Pull request by ArseniiPetrovich**
Accumulative PR for a lot of interconnected issues:

- [x] As for #76 issue - it might be not a really good idea to define all the role-specific variables inside a single node-level role, since it can be used in a dependent roles. But it should be definitely moved out of all.example file. We specifed roles/xxx/vars/main.yml as a .gitignore and renamed all the exitsing main.yml files to main.yml.example. Node names/node sizes and so on were moved to AWS subfolder as described in #104 issue. Also, as far as we decided not to merge sokol and core branches into single branch - there is no need to create group_vars/sokol or group_vars/core files.
- [x] #79 issue fixed in connection with #104.
- [x] #80 issue fixed.
- [x] #92 issue fixed - vagrant compatibility specified.
- [x] #99 and #104 issues were fixed. All the aws-related staff were moved to the aws/ subfolder and will be run as a separate playbook till we're bringing Terraform to live.
- [x] #102 fixed. Common tasks were moved to the preconf role.
- [x] #113 fixed. Now we have the same variable declaration. Good point of standardization.
- [x] #114 fixed. Also this fix will not affect future "CentOS support" PR as it already envisaged.
- [x] #115 fixed, defaults created. They usually should be overwritten by group_vars or user variables
- [x] #119 unused role removed
- [x] #123 unused variable removed
- [x] #110 fixed, files will be created with the rights permissions now
- [x] #118 all.yml.example file created
- [x] #120 added as optional task. Set "configure_extended_tcp_settings" variable to "true" to launch it.
- [x] #124 workaround created.

### CODE REVIEW

**Comment by phahulin** [comment]
Tried to launch an instance on aws:
```
cd aws
# created group_vars/all
ansible-playbook bootnode.yml
```
getting the following error:
```
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

 [WARNING]: While constructing a mapping from /home/xaxa/Work/ramdisk/deployment-playbooks/aws/bootnode.yml, line 62,
column 3, found a duplicate dict key (hosts). Using last defined value only.

ERROR! the role 'preconf' was not found in /home/xaxa/Work/ramdisk/deployment-playbooks/aws/roles:/home/xaxa/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/xaxa/Work/ramdisk/deployment-playbooks/aws

The error appears to have been in '/home/xaxa/Work/ramdisk/deployment-playbooks/aws/bootnode.yml': line 82, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - preconf
      ^ here
```
probably, preconfg should be removed from those yml files

**Comment by phahulin** [comment]
@ArseniiPetrovich few minor notes:
* there seems to be no need to have `hosts.example` file in `aws/` folder as there are no nodes initially
* `hosts` key is duplicated in `aws/{{ role }}.yml`, e.g. in [bootnode.yml](https://github.com/poanetwork/deployment-playbooks/pull/117/files#diff-9c48e276bf4250bd8e1932889081f789R64) (this bug is from the original playbook, not introduced by this PR, but fix it please)
* as we are getting rid of using `root` user, should we remove `remote_user = root` from ansible.cfg [here](https://github.com/poanetwork/deployment-playbooks/pull/117/files#diff-5c7908973afc7056baf5be661e11fc1bR11) and [here](https://github.com/poanetwork/deployment-playbooks/blob/master/ansible.cfg#L11)
* following the same argument, should we remove putting ssh-key for `root` [here](https://github.com/poanetwork/deployment-playbooks/blob/master/roles/preconf/tasks/main.yml#L2) and remove corresponding variables: [[1](https://github.com/poanetwork/deployment-playbooks/pull/117/files#diff-b95677b0fa78fb24aada7c5d1bf2f078R6)], [[2](https://github.com/poanetwork/deployment-playbooks/pull/117/files#diff-a30389506dc12c169bce1cbfb8c1f035R12)]

**Comment by ArseniiPetrovich** [comment]
For the last two points the answer is no, we shouldn't.
We are not getting rid of root user exactly. We are still using it to create a user and to do all the other things, that requires elevated permissions to execute.
If you want us to rewrite playbooks that will not use root at all - i think we will need another opened issue for that and, accordingly, it would be out of scope of this PR.
For the first two points - yes, I totally agree. I will upload the fix right now.

**Comment by phahulin** [comment]
I mean, should we remove the ability to connect as root? We still use it for tasks, but at this moment we additionally put ssh keys for root, so that user can connect as root, which is probably redundant. What do you think?

**Comment by phahulin** [comment]
Yes, I don't think it's possible to get rid of root for tasks, but we shouldn't grant ssh access if it's not essential. Let's discuss this in [a new issue](https://github.com/poanetwork/deployment-playbooks/issues/125).

**Pull request merged**
