### PR TITLE
Support CentOS as base OS

### LINKED ISSUE #90: Support for CentOS targets
Deployment playbooks support one base OS image at this time - Ubuntu 16.04. This issue requests support for CentOS 7.X as base image for POA nodes.

To add CentOS 7.x support:

- [x] Add CentOS base image to the local development environment
- [X] Add CentOS base image to the Terraform scripts
- [x] Change packages deployment method from `apt` to `yum` based on `ansible_os_family` variable
- [x] Fix issues with different package names on CentOS and Ubuntu
- [x] Fix issues with different configuration for the services on CentOS and Ubuntu
- [x] Verify changes by deploying nodes to CentOS and Ubuntu vms

Example of maintaining different set of tasks for different platforms:

```
# file: tasks.yml

- import_tasks: tasks_ubuntu.yml
  when: ansible_os_family == "Debian"

- import_tasks: tasks_centos.yml
  when: ansible_os_family == "RedHat"
```

### PR DESCRIPTION
**Pull request by lexsys27**
Fixes #90 

- [x] preconf role
  - [x] packages ( 092627a )
  - [X] chrony ( 909b507 )
- [x] node role ( 7a42f4f )
- [x] nginx role ( 5ee0f80 )
- [x] ufw (all node roles) ( 087df6c  )
- [x] specify the interpreter ( f80b6a6 )
- [x] add platform-dependent host groups to the Vagrantfile
- [x] verify changes
  - [x] bootnode
  - [x] validator
  - [x] moc
  - [x] explorer
  - [x] netstat

### CODE REVIEW

**Comment by phahulin** [comment]
Two problems while deploying a bootnode to aws:

1. by default aws does not allow connection as `root`, default username is `centos`. This should probably be refactored as part of https://github.com/poanetwork/deployment-playbooks/issues/101
Playbook also does not create a user named `ubuntu`.

2. it seems like bootnode-access role tries to connect to localhost and check connection status by running a python command (standard procedure), however it fails because sudo (on localhost) is not allowed
```
TASK [bootnode-access : Create bootnode security group] *****************************************************************************************************************
task path: /home/me/Work/deployment-playbooks/roles/bootnode-access/tasks/ec2.yml:2
Using module file /home/me/.local/lib/python2.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: me
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-fslxogtytmtpoliybzawdfllxfmyuvdb; /usr/bin/python'"'"' && sleep 0'
fatal: [52.54.169.206 -> localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "sudo: a password is required\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

**Comment by phahulin** [comment]
Also, when deploying ubuntu some pip dependencies are not installed:
```
fatal error: openssl/opensslv.h: No such file or directory
```

**Comment by phahulin** [comment]
@Ykisialiou do you think this PR can be closed now in favor of #144 ?

**Comment by Ykisialiou** [comment]
@phahulin  I suppose yes, #144 is doing the same and some commits from here are there now.

**Pull request closed without merging**
