### PR TITLE
Split playbook

### LINKED ISSUE #79: Split playbook based on node types
Currently all the node types plays are defined in `site.yml`. This issue suggests splitting the `site.yml` file into a set of files like `validator.yml`. Then these files are imported to the main file with `import_playbook` statement. This structure is modular and can be easily integrated with Terraform.

For example, to provision only the `validator` node one runs

```
ansible-playbook validator.yml
```

Current `validator.yml` moves to the `aws` subfolder as it contains aws-related code.

### PR DESCRIPTION
**Pull request by lexsys27**
Fixes #79

### CODE REVIEW

**Comment by phahulin** [comment]
@igorbarinov what this does basically, is it moves current files like `bootnode.yml`, `validator.yml` etc to a new `aws/` folder and then splits current `site.yml` file into separate role-specific playbooks which are named again `bootnode.yml`, `validator.yml` etc.

So, at the moment, users run
```
# create ec2 instance
ansible-playbook validator.yml
# update hosts file
ansible-playbook -i hosts site.yml
```

After this PR is merged, they'll run
```
# create ec2 instance
ansible-playbook aws/validator.yml
# update hosts file
ansible-playbook -i hosts validator.yml
```

I think this makes sense, but I request your approval because it involves changes in userland.

Also, @lexsys27  @igorbarinov let's not merge it right away after approval, because docs would need to be updated in many places.

**Comment by lexsys27** [comment]
@phahulin what is the workflow for updating documentation in your project?

Typically I see documentation maintaining in the same repository as code. Committer includes documentation changes in the same PR as code changes.

Other way is to version code and docs separately with semantic versioning,  for example.  Changes are accumulated until the next version is released. Documentation is updated for the released version.

**Comment by phahulin** [comment]
This repository has [its own wiki](https://github.com/poanetwork/deployment-playbooks/wiki), but most important part there is [list of all options](https://github.com/poanetwork/deployment-playbooks/wiki/Playbook-options)

By "docs" I meant our [main wiki](https://github.com/poanetwork/wiki/wiki) which contains various guides and instructions for users. It's typically updated by ourselves or certain members of community when needed.

**Comment by phahulin** [comment]
@igorbarinov I think we can safely merge it to `master` now so that new PRs don't introduce merge conflicts. `master` is not used in production, so we can update `sokol` and `core` later

**Comment by phahulin** [comment]
@lexsys27 if this is still relevant, please resolve conflicts

**Comment by ArseniiPetrovich** [comment]
Yes, it can be closed too.

**Pull request closed without merging**
